name: vpn_blank

on:
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  vpn_connect:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install OpenVPN
        run: |
          sudo apt update
          sudo apt install -y openvpn openvpn-systemd-resolved
      - name: Connect to Asee VPN
        uses: "kota65535/github-openvpn-connect-action@v2"
        with:
          config_file: .github/workflows/opsvpn.ovpn
          client_key: ${{ secrets.OPSVPN_KEY }}
      - name: Ping Something local
        run: ping -3 10.148.0.100
      - name: Ping something in the same network
        run: ping -3 10.148.0.8
